### ISSUE TITLE
Npm install/update breaks Timbits

### ISSUE THREAD

**Issue by pmwilliamson** [Postmedia-Archive/timbits#22]
Action: Update or install of timbits works fine, but will produce the following error now when running server.js

node server.js
## 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function app(req, res){ app.handle(req, res); } has no method
'register'
    at Object.serve (C:\nodeexperiments\node\mytimbits\node_modules\timbits\lib\
timbits.js:37:17)
    at Object.<anonymous> (C:\nodeexperiments\node\mytimbits\server.js:2:22)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
    at EventEmitter._tickCallback (node.js:192:40)

Notes:  This was working fine on Friday.  Seems like Express was just updated to 3.0 alpha and this comes down in an update or install...possibly the culprit?

Thanks,

Matt

**Comment by pmwilliamson** [comment]
Here is the "npm ls" as requested:

mytimbits@0.0.1 C:\nodeexperiments\node\mytimbits
├── coffee-script@1.2.0  extraneous
└─┬ timbits@0.5.2
  ├── coffeekup@0.3.1
  ├─┬ coloured-log@0.9.7
  │ ├── coloured@0.2.0
  │ └── log@1.3.0
  ├─┬ connect-assets@2.0.0-rc1
  │ ├── mime@1.2.2
  │ └── uglify-js@1.0.7
  ├─┬ connect-esi@0.2.1
  │ └─┬ styout@0.6.0
  │   ├── sty@0.6.1
  │   └── underscore@1.3.3
  ├─┬ connect-less@0.3.0
  │ ├── async@0.1.18
  │ └── less@1.3.0
  ├─┬ express@3.0.0alpha1
  │ ├── commander@0.5.2
  │ ├─┬ connect@2.1.2
  │ │ ├── crc@0.1.0
  │ │ ├── formidable@1.0.9
  │ │ ├── mime@1.2.4
  │ │ └── qs@0.4.2
  │ ├── debug@0.6.0
  │ ├── mime@1.2.5
  │ └── mkdirp@0.3.1
  ├─┬ jsonp-filter@0.0.3
  │ └─┬ styout@0.6.0
  │   ├── sty@0.6.1
  │   └── underscore@1.3.3
  ├─┬ optimist@0.3.1
  │ └── wordwrap@0.0.2
  ├─┬ pantry@0.3.2
  │ └─┬ xml2js@0.1.13
  │   └── sax@0.4.0
  ├── request@2.9.202
  └─┬ run@0.2.3
    └─┬ minimatch@0.2.4
      └── lru-cache@1.0.6

**Comment by mehtryx** [comment]
Working through this, the issue does not occur with node 0.4.11, it installs the older version of express 2.5.9

The 3.0alpha release requires node 5.0 or higher so this may explain why it will work for some and even on some vendor sites still but not on development machines.

Also noticed that the last fix for directories breaks on node 0.4.11, it appears we need to make two changes to timbits 0.5.2

First - based on changelog for node the current version of timbits uses functionality of fs.mkdir which was changed in node 6.1 therefore the:

"engines": { "node": ">= 0.4.5" }

needs to be changed to 

"engines": { "node": ">= 0.6.1" }

Second change required is a limit to express as the 3.0alpha is not compatible, so change: 

"express": ">= 2.5.6"

to

"express": ">= 2.5.6 < 3.0"

That's the proposed changes, we'd need to discuss if that's what we want ( especially the nod engine version with regards to deployment on third parties... ) and then push a new version out.  Will discuss with Ed.

**Comment by mehtryx** [comment]
fixes available in pull request: https://github.com/Postmedia/timbits/pull/23

**Comment by mred9** [comment]
v0.5.3 has been published with these changes to the package file.
